# autogenerated by txs
\duinfamily#S
\durmfamily#S
\dusffamily#S
\duttfamily#S
\textdubf #S
\textdubf#S
\textduin #S
\textduin#S
\textdurm #S
\textdurm#S
\textdusf #S
\textdusf#S
\textdusl #S
\textdusl#S
\textdutt #S
\textdutt#S
