# autogenerated by txs
\begin{corollary}#S
\begin{definition}#S
\begin{lemma}#S
\begin{proposition}#S
\begin{theorem}#S
\end{corollary}#S
\end{definition}#S
\end{lemma}#S
\end{proposition}#S
\end{theorem}#S
\intff{arg1}{arg2}#S
\intoo{arg1}{arg2}#S
\thedummy
\ud#S
